spring:
  application:
    name: szs-YoungJunKim
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:szs
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

  jwt:
    secret: "and0c2VjcmV0a2V5and0c2VjcmV0a2V5and0c2VjcmV0a2V5and0c2VjcmV0a2V5and0c2VjcmV0a2V5"
    access:
      expiration: 600000 # 10분
    refresh:
      expiration: 86400000 # 24시간

logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE


springdoc:
  swagger-ui:
    path: /3o3/swagger.html

